require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5
  EnabledByDefault: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Copyright:
  Notice: '# Copyright 2012\-2021\. All rights reserved'
